# spring:
#   datasource:
#     url: jdbc:h2:mem:default # ?useTimezone=true&serverTimezone=UTC
#     username: sa
#     password: 
#     driverClassName: org.h2.Driver
#   jpa:
#     show-sql: false
#     # properties:
#     #   hibernate:
#     #     format_sql: true
#   h2:
#     console:
#       enabled: true
#       path: /h2-console

cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://frota.segsat.com
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest-whit-spring-boot-and-java?useTimezone=true&serverTimezone=UTC
    username: root
    password: "@$Kinos96883012$@"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true