spring:
  datasource:
    url: jdbc:h2:mem:default # ?useTimezone=true&serverTimezone=UTC
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    # properties:
    #   hibernate:
    #     format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console